services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel123
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
